config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Sidekiq::Web.use(Auth)

Rails.application.routes.draw do
  Healthcheck.routes(self)

  concern :paginatable do
    get "(page/:page)", action: :projects_table, on: :collection, as: ""
  end

  mount Sidekiq::Web, at: "/sidekiq"
  mount AuthHelper.with_auth(Yabeda::Prometheus::Exporter), at: "/metrics", via: :get if AppConfig.metrics?
  mount API => "/"

  root AppConfig.anonymous_access ? "projects#index" : "sessions#new"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :projects, only: %i[index create update destroy] do
    scope module: :update do
      resources :jobs, only: [] do
        put "execute", on: :member
        put "toggle", on: :member
      end

      resources :runs, only: [:show]
    end
  end

  get "/projects/table", to: "projects#table", concerns: :paginatable, as: "projects_table"
end

app/views/shared/_alert.html.erb
<% extra_classes = local_assigns.fetch(:extra_classes, []) %>
<% classes = ["alert", "alert-#{alert_type}", "alert-dismissible", "fade", "show", "mt-1"] %>
<% classes += extra_classes unless extra_classes.empty? %>

<div class="<%= classes.join(" ") %>" id="alert-message">
  <strong><%= message %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_header.html.erb
<% klazz = %w[btn btn-primary btn-sm] %>

<div class="d-flex border-bottom sticky-top bg-light-subtle" id="header">
  <nav class="ms-3 mt-3">
    <ol class="breadcrumb" style="--bs-breadcrumb-divider: '>';">
      <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
      <% pages.each_with_index do |page, index| %>
        <li class="<%= "breadcrumb-item #{pages.size - 1 == index ? 'active' : ''}".strip %> %>"><%= page %></li>
      <% end %>
    </ol>
  </nav>
  <div class="ms-auto me-3 btn-group">
    <button type="button" class="btn btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      About
    </button>
    <ul class="dropdown-menu">
      <li><h6 class="dropdown-header"><%= "v#{version}" %></h6></li>
      <li><%= button_to "Documentation", "https://dependabot-gitlab.gitlab.io/dependabot", class: "dropdown-item" %></li>
      <% unless AppConfig.anonymous_access %>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to "Logout", logout_path, method: :delete, class: "dropdown-item" %></li>
      <% end %>
    </ul>
  </div>
</div>