config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Sidekiq::Web.use(Auth)

Rails.application.routes.draw do
  Healthcheck.routes(self)

  concern :paginatable do
    get "(page/:page)", action: :projects_table, on: :collection, as: ""
  end

  mount Sidekiq::Web, at: "/sidekiq"
  mount AuthHelper.with_auth(Yabeda::Prometheus::Exporter), at: "/metrics", via: :get if AppConfig.metrics?
  mount API => "/"

  root AppConfig.anonymous_access ? "projects#index" : "sessions#new"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :projects, only: %i[index create update destroy] do
    scope module: :update do
      resources :jobs, only: [] do
        put "execute", on: :member
        put "toggle", on: :member
      end

      resources :runs, only: [:show]
    end
  end

  get "/projects/table", to: "projects#table", concerns: :paginatable, as: "projects_table"
end

app/models/project.rb
# frozen_string_literal: true

# Gitlab project
#
# @!attribute id
#   @return [Integer]
# @!attribute name
#   @return [String]
# @!attribute forked_from_id
#   @return [Integer]
# @!attribute forked_from_name
#   @return [String]
# @!attribute webhook_id
#   @return [Integer]
# @!attribute web_url
#   @return [String]
# @!attribute gitlab_access_token
#   @return [String]
# @!attribute merge_requests
#   @return [Array<MergeRequest>]
# @!attribute vulnerability_issues
#   @return [Array<VulnerabilityIssue>]
# @!attribute update_jobs
#   @return [Array<Update::Job>]
# @!attribute configuration
#   @return [Configuration]
class Project
  include Mongoid::Document

  paginates_per 10

  unalias_attribute :id

  field :name, type: String
  field :id, type: Integer
  field :forked_from_id, type: Integer
  field :forked_from_name, type: String
  field :webhook_id, type: Integer
  field :web_url, type: String
  field :gitlab_access_token, type: EncryptedString

  field :last_run_status, type: String
  field :last_update_run_at, type: DateTime

  has_many :merge_requests, dependent: :destroy
  has_many :vulnerability_issues, dependent: :destroy
  has_many :update_jobs, class_name: "Update::Job", dependent: :destroy

  embeds_one :configuration

  index({ id: 1 }, { unique: true })
  index({ name: 1 }, { unique: true })
  index(name: "text")

  # All open merge requests
  #
  # @param [String] package_ecosystem
  # @param [String] directory
  # @return [Array<MergeRequest>]
  def open_merge_requests(package_ecosystem:, directory:)
    merge_requests.where(
      package_ecosystem: package_ecosystem,
      directory: directory,
      state: "opened"
    )
  end

  # Project open merge requests
  #
  # @param [String] dependency_name
  # @param [String] directory
  # @return [Array<MergeRequest>]
  def open_dependency_merge_requests(dependency_name, directory)
    merge_requests
      .where(main_dependency: dependency_name, directory: directory, state: "opened")
      .compact
  end

  # :reek:LongParameterList

  # Open superseded merge requests
  #
  # @param [String] package_ecosystem
  # @param [String] directory
  # @param [String] update_from
  # @param [Integer] mr_iid
  # @return [Array<MergeRequest>]
  def superseded_mrs(package_ecosystem:, directory:, update_from:, mr_iid:)
    merge_requests
      .where(
        update_from: update_from,
        package_ecosystem: package_ecosystem,
        directory: directory,
        state: "opened"
      )
      .not(iid: mr_iid)
      .compact
  end

  # Open vulnerability issues
  #
  # @param [String] package_ecosystem
  # @param [String] directory
  # @param [String] package
  # @return [Array<VulnerabilityIssue>]
  def open_vulnerability_issues(package_ecosystem:, directory:, package:)
    vulnerability_issues
      .where(
        directory: directory,
        package: package,
        package_ecosystem: package_ecosystem,
        status: "opened"
      )
  end

  # Return projects hash representation
  #
  # @return [Hash]
  def to_hash
    {
      id: id,
      name: name,
      forked_from_id: forked_from_id,
      forked_from_name: forked_from_name,
      webhook_id: webhook_id,
      web_url: web_url,
      configuration: configuration&.updates
    }
  end

  class Entity < Grape::Entity
    expose :id, documentation: { type: Integer, desc: "Project ID" }
    expose :name, documentation: { type: String, desc: "Project full path" }
    expose :forked_from_id, documentation: { type: Integer, desc: "Forked from project ID" }
    expose :forked_from_name, documentation: { type: String, desc: "Forked from project full path" }
    expose :webhook_id, documentation: { type: Integer, desc: "Project webhook ID" }
    expose :web_url, documentation: { type: String, desc: "Project web URL" }
    expose :configuration, using: Configuration::Entity

    # Example response hash
    #
    # @return [Hash]
    def self.example_response
      {
        id: 1,
        name: "foo/bar",
        forked_from_id: 2,
        forked_from_name: nil,
        webhook_id: 3,
        web_url: "https://gitlab.com/foo/bar",
        configuration: Configuration::Entity.example_response
      }
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!

  # Render index projects page
  #
  # @return [void]
  def index; end

  # Render projects table
  #
  # @return [void]
  def table
    query = params[:active] == "true" ? { configuration: { "$ne" => nil } } : { configuration: nil }
    projects = if params[:project_name].blank?
                 Project.where(query).order(name: :asc).page(params[:page])
               else
                 Project.where("$text" => { "$search" => params[:project_name] })
                        .where(query).order(name: :asc)
                        .page(params[:page])
               end
    return render partial: "empty_content" if projects.empty?

    render partial: "projects_table", locals: { projects: projects }
  rescue StandardError => e
    render partial: "shared/alert", locals: { alert_type: "danger", message: "Oops, something went wrong: #{e}" }
  end

  # Add new project
  #
  # @return [void]
  def create
    project_name = params.require(:project_name)
    access_token = params[:access_token].presence

    existing_project = find_project(name: project_name)
    return notify(:warning, "Project already exists!") if existing_project

    project = Dependabot::Projects::Creator.call(params.require(:project_name), access_token: access_token)
    return notify(:warning, "Project without configuration added!") unless project.configuration

    Cron::JobSync.call(project)
    notify(:success, "Project added successfully!")
  rescue StandardError => e
    notify(:error, e.message)
  end

  # Sync existing project
  #
  # @return [void]
  def update
    project = find_project(id: params.require(:id))

    updated_project = Dependabot::Projects::Creator.call(project.name, access_token: project.gitlab_access_token)
    Cron::JobSync.call(updated_project)

    notify(:success, "Project synced successfully!")
  rescue StandardError => e
    notify(:error, e.message)
  end

  # Delete existing project
  #
  # @return [void]
  def destroy
    project = find_project(id: params.require(:id))
    Dependabot::Projects::Remover.call(project)

    notify(:success, "Project deleted successfully!")
  rescue StandardError => e
    notify(:error, e.message)
  end

  private

  # Add notification popup
  #
  # @param [Symbol] type
  # @param [String] message
  # @return [void]
  def notify(type, message)
    send("notify_#{type}", message) { redirect_to(projects_path) }
  end
end

app/views/projects/_add_project.html.erb
<div class="modal fade" id="newProjectModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add new project</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: projects_path, method: :post do |f| %>
          <div class="mb-3">
            <%= f.text_field :project_name, class: "form-floating form-control", placeholder: "Full project path" %>
          </div>
          <div class="mb-4">
            <%= f.password_field :access_token, class: "form-floating form-control", placeholder: "Access token: (optional)" %>
          </div>
          <div class="d-flex">
            <div class="ms-auto">
              <button type="button" class="btn btn-outline-secondary me-1" data-bs-dismiss="modal">Cancel</button>
              <%= f.submit "Add", id: :add_project, class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_delete_project.html.erb
<div class="modal fade" id="delete-project-modal-<%= id %>" data-bs-keyboard="false" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5">Are you sure you want to delete project?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= button_to "Delete", project_path(id), method: :delete, title: "Remove project", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_empty_content.html.erb
<div class="d-flex flex-column align-items-center">
  <%= image_tag("empty-folder.png", class: "img-fluid", style: "max-width: 25%") %>
  <h2 class="text-center">No projects found</h2>
</div>

app/views/projects/_projects_table.html.erb
<% projects.each do |project| %>
  <div class="card mb-2">
    <h5 class="card-header">
      <%= link_to_if project.web_url, project.name, project.web_url %>
    </h5>
    <div class="card-body px-0 pt-0">
      <table class="table table-striped mx-0">
        <thead class="table-light">
          <tr>
            <th scope="col">Enabled</th>
            <th scope="col">Status</th>
            <th scope="col">Ecosystem</th>
            <th scope="col">Directory</th>
            <th scope="col">Cron</th>
            <th scope="col">Executed</th>
            <th scope="col">Open merge requests</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody class="table-group-divider" data-controller="job">
          <% if project.update_jobs.empty? %>
            <tr>
              <td colspan="8">No jobs configured</td>
            </tr>
          <% else %>
            <div>
              <% project.update_jobs.each do |job| %>
                <% project_name = project.name %>
                <% ecosystem = job.package_ecosystem %>
                <% directory = job.directory %>
                <% config_entry = project.configuration.entry(package_ecosystem: ecosystem, directory: directory) %>
                <% next log(:error, "Tried to render job entry but missing configuration entry for project '#{project_name}=>#{ecosystem}=>#{directory}'") unless config_entry %>
                <tr>
                  <td>
                    <div class="form-check form-switch">
                      <%= check_box_tag "toggle",
                                        toggle_project_job_path(project.id, job.id),
                                        job.enabled,
                                        autocomplete: :off,
                                        class: "form-check-input",
                                        data: {
                                          action: "job#toggle",
                                          testid: "#{project_name}-#{ecosystem}-#{directory}-toggle"
                                        }
                      %>
                    </div>
                  </td>
                  <td><%= status_icon(job.last_run_status, width: "18", height: "18") %>
                  <td><%= ecosystem %></td>
                  <td><%= directory %></td>
                  <td><%= job.cron %></td>
                  <% last_executed = job.last_executed %>
                  <td><%= "#{time_ago_in_words(last_executed)} ago" if last_executed %>
                  <td>
                    <%=
                      mrs = open_merge_requests(project, job.package_ecosystem, job.directory).length
                      link_to_if(mrs > 0, mrs, open_mrs_url(project, config_entry))
                    %>
                  </td>
                  <td>
                    <div class="d-flex justify-content-end">
                      <button class="btn btn-primary btn-sm me-1"
                              data-action="job#execute"
                              data-testid="<%= "#{project_name}-#{ecosystem}-#{directory}-execute"%>"
                              data-url="<%= execute_project_job_path(project.id, job.id) %>"
                      >
                        Execute
                      </button>
                      <%= button_to "View Logs",
                                    project_run_path(project.id, job.last_run.id),
                                    method: :get,
                                    title: "View job logs",
                                    class: "btn btn-primary btn-sm" if job.last_run
                      %>
                    </button>
                  </td>
                </tr>
              <% end %>
            </div>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex ms-2">
        <%= button_to "Sync", project_path(project.id), method: :put, title: "Sync project configuration", class: "btn btn-primary btn-sm me-1" %>
        <button type="button" class="btn btn-danger btn-sm" title="Delete project" id="delete-project" data-bs-toggle="modal" data-bs-target="#delete-project-modal-<%= project.id %>">Delete</button>
      </div>
      <%# TODO: remove hacky modal duplicates when single project page is implemented %>
      <%= render partial: "delete_project", locals: { id: project.id } %>
    </div>
  </div>
<% end %>
<%= paginate projects %>

app/views/projects/index.html.erb
<% provide(:title, "Dependabot GitLab") %>

<%= render partial: "shared/header", locals: { pages: ["Projects"] } %>
<% flash.each do |message_type, message| %>
  <div class="mx-5">
    <%= render partial: "shared/alert", locals: { alert_type: message_type, message: message } %>
  </div>
<% end %>
<div class="d-flex mx-5">
  <div class="container-fluid mt-2">
    <div class="d-flex justify-content-between">
      <div>
        <h2>Projects</h2>
      </div>
      <div>
        <button type="button" class="btn btn-primary" id="new-project" data-bs-toggle="modal" data-bs-target="#newProjectModal">New project</button>
      </div>
    </div>
    <%= render partial: "add_project" %>
    <div data-controller="projects" data-projects-url-value=<%= projects_table_path %>>
      <div class="row bottom-border mt-3 mb-3">
        <ul class="nav nav-tabs bottom-border-0">
          <li class="nav-item" role="presentation">
            <button class="nav-link project-tab active" title="Active projects" id="active-tab" data-bs-toggle="tab" data-bs-target="#active" type="button" data-action="projects#selectTab">Active</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link project-tab" title="Projects without configuration" id="inactive-tab" data-bs-toggle="tab" data-bs-target="#inactive" type="button" data-action="projects#selectTab">Inactive</button>
          </li>
          <li class="ms-auto">
            <%= form_with url: projects_table_path,
                          method: :get,
                          id: "filter-form",
                          data: { action: "projects#filter" },
                          class: "form-control border-0 py-0 pe-0 mt-1" do |form| %>
            <%= form.search_field :project_name, placeholder: "Filter by name", id: "search-input", class: "rounded-1", style: "min-width: 300px" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="active" role="tabpanel" data-projects-target="tabPane">
          <div class="spinner-border mt-3" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
        <div class="tab-pane fade" id="inactive" role="tabpanel" data-projects-target="tabPane">
          <div class="spinner-border mt-3" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>